# Generated by Django 3.1.2 on 2020-11-27 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
                ('symbol', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('tweetID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('text', models.TextField(max_length=280)),
                ('userID', models.TextField()),
                ('score', models.FloatField()),
                ('interactions', models.IntegerField()),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_covidStocks.company')),
            ],
        ),
        migrations.CreateModel(
            name='ObservedStock',
            fields=[
                ('stockID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('price', models.FloatField()),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_covidStocks.company')),
            ],
        ),
        migrations.CreateModel(
            name='ExpectedStock',
            fields=[
                ('derivedStockID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('model', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('price', models.FloatField()),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_covidStocks.company')),
            ],
        ),
    ]
