# Generated by Django 3.1.2 on 2020-11-03 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_covidStocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='stockID',
        ),
    ]
